### ISSUE TITLE
Error: Current branch (tests/bumpversion) does not track anything. Cannot push.

### ISSUE THREAD

**Issue by JohnPreston** [dmerejkowsky/tbump#87] opened 2021-03-04 00:05 UTC
I am getting the following error
```bash
Error: Current branch (tests/bumpversion) does not track anything. Cannot push.
```

Which makes very little sense IMHO. I was tracking issues from bump2version which led me to this project, and I never had to set the git tracking for the branch to the remote just to bump the version and add a tag.

That said, am I doing something wrong?

Here is the config file (edited) after running `tbump init 0.12.2`

```config
[tool.tbump.version]
current = "0.12.2"

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (?:\-(?P<rc>[\S]+))?
  '''

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[tool.tbump.file]]
src = "setup.py"

[[tool.tbump.file]]
src = "ecs_composex/__init__.py"

[[tool.tbump.before_commit]]
name = "Files format"
cmd = "make conform"
```
Only way I get it to work as expected is via `tbump --only-patch`
Also, your default behavior is to want to push to the branch, which again is rather different from bump2version which only creates the tag and commit message for it but is not trying to push something for me.

Maybe instead of `--no-push` as an option, have `--push` as an option for people wishing to push as they create the tag.

Many thanks for your help and consideration :) 

PS: So much easier way to define the version than bump2version ..... :100: (minus the above details)

**Comment by dmerejkowsky** [comment] 2021-03-04 11:58
> Only way I get it to work as expected is via tbump --only-patch

This is weird. `--no-push` should have been enough.

> The default behavior is to want to push to the branch

Yup. The intention is that once the commit and the tag are created, you want to push them both. Before using tbump, I often ended up pushing the tag without the branch or vice-versa :)

The problem is that we can't just run `git push --tags` because the behavior would depend on the git configuration - 
see https://git-scm.com/docs/git-config#Documentation/git-config.txt-pushdefault for details.

So instead we ask git for the tracking ref of the local branch and extract both the remote branch and the remote name, which allows us to run `git push <origin> <tag>` and `git push <origin> <remote-branch>` which only pushes the tag and commit we just created.


> Maybe instead of --no-push as an option, have --push as an option for people wishing to push as they create the tag.

Well - I don't think we'll manage to have a default behavior that pleases everyone :)

Also, not that we *don't* check if the local branch tracks something when `--no-push` is used.

> PS: So much easier way to define the version than bump2version ..... 100 (minus the above details)

Thanks - that was the goal all along :)

**Comment by dmerejkowsky** [comment] 2021-06-28 11:02
> This is weird. --no-push should have been enough.

I believe this bug has been fixed. Closing.

**Closed by dmerejkowsky** 2021-06-28 11:02 UTC

**Comment by mathieulongtin** [comment] 2022-06-14 18:45
This seems to happen if you:
1. create a new git repo (init)
2. push it to a remote
3. try to tbump it

If you start with a "git clone", it's not an issue.

`git config -l` output for non working repo (init + push):
```
branch.main.remote=git@gitlabs.com:domain/project.git
branch.main.merge=refs/heads/main
```

`git config -l` for repo where tbump works:
```
remote.origin.url=git@gitlabs.com:domain/project.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
```

**Comment by dmerejkowsky** [comment] 2022-06-22 10:17
@mathieulongtin : indeed, this is one scenario where the current branch would not track anything. There are more.
